/*
 * Copyright 2025-2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.ohs.fhir

import com.ionspin.kotlin.bignum.decimal.BigDecimal

/**
 * Canonicalizes unit values to UCUM base units.
 *
 * For details of UCUM, see http://unitsofmeasure.org/
 *
 * For using UCUM with FHIR, see https://www.hl7.org/fhir/ucum.html
 *
 * For the implementation of UCUM with FHIR, see https://github.com/FHIR/Ucum-java
 *
 * JVM targets (Android, Desktop) provide a real implementation backed by `org.fhir:ucum`. iOS
 * currently returns the original value unchanged — a native UCUM port is not yet available.
 */
internal expect object UnitConverter {

  /**
   * Returns the canonical form of a UCUM Value if it is supported in the UCUM library; otherwise
   * returns the original value.
   *
   * The canonical form is generated by normalizing [value] to UCUM base units, used to generate
   * canonical matches on Quantity Search.
   *
   * For example a value of 1000 mm will return 1 m.
   */
  fun getCanonicalFormOrOriginal(value: UcumValue): UcumValue
}

internal class ConverterException(message: String, cause: Throwable? = null) :
  Exception(message, cause)

internal data class UcumValue(val code: String, val value: BigDecimal)
