/*
 * Copyright 2023-2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.ohs.fhir.index

import com.google.fhir.model.r4.Resource as KotlinFhirResource
import com.google.fhir.model.r4.terminologies.ResourceType
import dev.ohs.fhir.getResourceClass
import kotlin.test.assertEquals
import org.hl7.fhir.r4.model.Resource
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import sun.misc.Unsafe

@RunWith(Parameterized::class)
class SearchParameterRepositoryGeneratedTest(private val resource: Resource) {
  @Test
  fun testResources() {
    // KMP bridge: getSearchParamList needs a kotlin-fhir Resource, but kotlin-fhir's data classes
    // have many required fields with no defaults — neither JSON deserialisation nor reflective
    // constructor calls work universally. The dispatch inside getSearchParamList only reads
    // `resource.resourceType`, which is `this::class.simpleName`, so any instance with the right
    // runtime class is enough. Allocate one without calling any constructor.
    val klass = getResourceClass<KotlinFhirResource>(resource.resourceType.name).java
    val kotlinFhirResource = unsafe.allocateInstance(klass) as KotlinFhirResource
    assertEquals(
      getSearchParamListReflection(resource).toSet(),
      getSearchParamList(kotlinFhirResource).toSet(),
    )
  }

  private fun getSearchParamListReflection(resource: Resource): MutableList<SearchParamDefinition> {
    val searchParams = getBaseSearchParameters()
    searchParams.addAll(
      resource.javaClass.fields
        .asSequence()
        .mapNotNull {
          it.getAnnotation(ca.uhn.fhir.model.api.annotation.SearchParamDefinition::class.java)
        }
        .filter { it.path.isNotEmpty() }
        .map {
          SearchParamDefinition(
            it.name,
            SearchParamType.valueOf(it.type.uppercase()),
            it.path,
          )
        }
        .toMutableList(),
    )

    return searchParams
  }

  // We are adding these manually because they don't exists in HAPI FHIR java classes
  private fun getBaseSearchParameters(): MutableList<SearchParamDefinition> {
    val searchParams = mutableListOf<SearchParamDefinition>()
    searchParams.add(
      SearchParamDefinition(
        "_id",
        SearchParamType.TOKEN,
        "${resource.resourceType.name}.id",
      ),
    )
    searchParams.add(
      SearchParamDefinition(
        "_lastUpdated",
        SearchParamType.DATE,
        "${resource.resourceType.name}.meta.lastUpdated",
      ),
    )
    searchParams.add(
      SearchParamDefinition(
        "_profile",
        SearchParamType.URI,
        "${resource.resourceType.name}.meta.profile",
      ),
    )
    searchParams.add(
      SearchParamDefinition(
        "_security",
        SearchParamType.TOKEN,
        "${resource.resourceType.name}.meta.security",
      ),
    )
    searchParams.add(
      SearchParamDefinition(
        "_source",
        SearchParamType.URI,
        "${resource.resourceType.name}.meta.source",
      ),
    )
    searchParams.add(
      SearchParamDefinition(
        "_tag",
        SearchParamType.TOKEN,
        "${resource.resourceType.name}.meta.tag",
      ),
    )

    return searchParams
  }

  private companion object {
    private val unsafe: Unsafe =
      Unsafe::class.java.getDeclaredField("theUnsafe").apply { isAccessible = true }.get(null)
        as Unsafe

    @Parameterized.Parameters @JvmStatic fun data(): List<Resource> = getAllResources()

    // Engine has this generated by the test-helper codegen task; the destination's codegen only
    // emits production `getSearchParamList`, so we materialise the equivalent list locally by
    // enumerating kotlin-fhir's `ResourceType` and instantiating each HAPI counterpart reflectively.
    private fun getAllResources(): List<Resource> =
      ResourceType.entries.mapNotNull { type ->
        try {
          @Suppress("UNCHECKED_CAST")
          val cls = Class.forName("org.hl7.fhir.r4.model.${type.name}") as Class<out Resource>
          cls.getDeclaredConstructor().newInstance()
        } catch (_: Throwable) {
          null
        }
      }
  }
}
